movie_recommender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from movies import views

app_name = 'movies'

urlpatterns = [
    path('', views.UserHomePageView.as_view(), name='index'),
    path('<int:pk>/', views.UserMovieDetailView.as_view(), name='movie_detail'),
    path('watchlist/', views.UserWatchListView.as_view(), name='movie_watchlist'),
    path('recommend/', views.UserRecommendView.as_view(), name='recommend_movies'),
]

assets/templates/partials/form_template.html
{% for field in form %}
<link rel="stylesheet" href="../static/css/form_template.css">
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="form-label col-sm-2" for="movie_title">{{ field.label_tag }}</label>
        <div class="col-sm-10 input">{{ field }}</div>
    </div>
{% endfor %}

assets/templates/partials/navbar.html
{% with request.resolver_match.url_name as URL_NAME %}
<link rel="stylesheet" href="../../static/css/navbar.css">
<nav class="navbar navbar-expand-lg bg-navbar navbar-inverse navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: #fff;" href="/">My Recommender</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link{% if URL_NAME == 'index' %} active{% endif %}" href="{% url 'movies:index' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link{% if URL_NAME == 'movie_watchlist' %} active{% endif %}" href="{% url 'movies:movie_watchlist' %}"> Watchlist</a>
        </li>

      </ul>
      <ul class="navbar-nav">
        {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'signup' %}" class="nav-link{% if URL_NAME == 'signup' %} active{% endif %}">
              <span aria-hidden="true">SignUp</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link{% if URL_NAME == 'login' %} active{% endif %}">
              <span aria-hidden="true">Login</span>
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link{% if URL_NAME == 'logout' %} active{% endif %}">
              <span aria-hidden="true">Logout</span>
            </a>
          </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
{% endwith %}

assets/templates/partials/pagination.html
{% load paginator_tags %}
{% proper_paginate page_obj.paginator page_obj.number as page_range %}

<nav aria-label="Data paginator">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        {% if request.GET.q %}
        <a class="page-link" href="?q={{request.GET.q}}&page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
    {% endif %}
    {% for page_idx in page_range %}
      {% if page_idx == page_obj.paginator.ELLIPSIS %}
        <li class="page-item">
          <span class="page-link">{{ page_idx }}</span>
        </li>
      {% else %}
        <li class="page-item {% if page_idx == page_obj.number %}active{% endif %}">
          {% if request.GET.q %}
          <a class="page-link " href="?q={{request.GET.q}}&page={{page_idx}}">{{page_idx}}</a>
          {% else %}
          <a class="page-link " href="?page={{page_idx}}">{{page_idx}}</a>
        {% endif %}
        </li>
      {% endif %}

    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        {% if request.GET.q %}
        <a class="page-link" href="?q={{request.GET.q}}&page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
    {% endif %}
  </ul>
</nav>