movie_recommender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from movies import views

app_name = 'movies'

urlpatterns = [
    path('', views.UserHomePageView.as_view(), name='index'),
    path('<int:pk>/', views.UserMovieDetailView.as_view(), name='movie_detail'),
    path('watchlist/', views.UserWatchListView.as_view(), name='movie_watchlist'),
    path('recommend/', views.UserRecommendView.as_view(), name='recommend_movies'),
]

assets/templates/list.html
{% extends 'base/base.html'%}
{% block body %}

  {% if not request.user.is_authenticated %}
    <br>
  {% else %}
    <h2 style="color:#fff" class="text-center">Welcome
      {{user.username}}!!</h2>
  {% endif %}

  <div class="container">
    <div class="col-xs-6 col-xs-offset-3">
      <form class="row" role="search" method="get">

        <div class="input-group mb-3 input-group-lg">
          <input style="margin-left: -45px; " type="text" class="form-control" placeholder="Search movies" aria-label="Search Movies" aria-describedby="search-btn" name="q" value="{{ request.GET.q }}">
          <button class="btn btn-success" style="background-color: black;" type="submit" id="search-btn">Search</button>
        </div>

      </form>

    </div>
  </div>

  <p class="text-start">
    <span style="float:right;">
      <a href="{% url 'movies:recommend_movies' %}" class="btn">
        <button style="color:white; background-color: black;padding:10px">Get Movie Recommendation</button>
      </a>
      <h2 style="color: white; text-align: center;">Movie List</h2>
    </span>
  </p>
  <hr>
  <br>

  <!-- Movie list -->
  <div class="row">
    {% if object_list %}
      {% for movie in object_list %}
        <div class="col-sm-2 col-md-2">
          <div class="thumbnail" style="border-radius: 22px 22px 22px 22px;">

            <h6 class="text-center text-light" style="margin-left:-40px";>{{movie.title}}</h6>

            <a href="{% url 'movies:movie_detail' movie.pk %}">
              <img src="{{ movie.get_image}}" class="img-fluid" style="border-radius: 22px ; width: 250px; padding-bottom: 30px;">
            </a>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>

  {% if page_obj %}
    <div class="row mt-3">
      {% include 'partials/pagination.html' %}

    </div>
  {% endif %}

</div>

{% endblock %}

assets/templates/login.html
{% extends 'base/base.html'%}
{% block title %}Log In{% endblock %}

{% block body %}
<link rel="stylesheet" href="../static/css/login.css">
<div class="container">
    <div class="frame">
        <div class="nav">
           <h1>Log In</h1>
            </div>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                   <div>
                       <form class="form-signin" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- username -->
                        <label  for="id_username">
                            Username:
                        </label>
                        <input class="form-styling" id="id_username" type="text" name="username" placeholder="" autocomplete="off" /> 
                        <!-- password -->
                        <label for="id_password">
                            Password:
                        </label>
                        <input id="id_password"  name="password" type="password" class="form-styling" autocomplete="off">
                        <!-- login link -->
                        <div class="btn-animate">
                             <button class="btn-signin" type="submit">Login to your account</button> 
                        </div>
                       </form>
                   </div>
                   <div class="forgot"> Don't have an account? <a href="{% url 'signup' %}">Click here</a> to register. </div>
               
        
    </div>

</div>

{% endblock %}

assets/templates/signUp.html
{% extends 'base/base.html'%}
{% block title %}Register{% endblock %}
{% block body %}
<link rel="stylesheet" href="../static/css/signup.css">
  <div class="container">

    <div class="frame">
      
            <div class="nav">
              <h1>Register for an Account</h1>
               </div>
            
            {% if error_message %}
              <p>
                <strong>{{ error_message }}</strong>
              </p>
            {% endif %}
            <div>
              <form  class="form-signin" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'partials/form_template.html' %}
                 
                <div class="btn-animate">
                  <button class="btn-signin" type="submit">Login to your account</button> 
             </div>
              </form>
            </div>
           
          <div class="forgot">
            Already have an account?
            <a href="{% url 'login' %}">Click here</a>
            to log in.
          </div>
       
    </div>

  </div>

{% endblock %}